services:
  backend:
    build: backend/.
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
  frontend:
    build: frontend/.
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080
    volumes:
      - ./frontend:/app