name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [frontend, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and Push Docker image
        env:
          IMAGE_NAME: shinyamaeda/sf6-qa-chat-${{ matrix.component }}:latest
          DOCKERFILE_PATH: ${{ matrix.component }}
        run: |
          docker build -t $IMAGE_NAME $DOCKERFILE_PATH
          docker push $IMAGE_NAME

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Run only when manually triggered

    steps:
    - name: Deploy to Production
      run: echo deploy
